[package]
name = "noughts-and-crosses-gtk"
version = "0.0.1"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/noughts-and-crosses-gtk/"
repository = "https://gitlab.com/efunb/noughts-and-crosses-gtk"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pango = "0.6.0"
[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

[profile.release]
lto = true